/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Toolkit;
import java.time.LocalTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author John T Lazaro
 */
public class BankHome extends javax.swing.JFrame {

    /**
     * Creates new form BankHome
     */
    public BankHome() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        new Clock().start();
    }
    class Clock extends Thread{
        @Override
        public void run(){
            while(true){
                try{
                    LocalTime time=LocalTime.now();
                    String h=Integer.toString(time.getHour());
                    String m=Integer.toString(time.getMinute());
                    String s=Integer.toString(time.getSecond());
                    clock.setText(h+":"+m+":"+s);
                    sleep(1000);

                }catch(InterruptedException e){
                    //ignore erro
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        bankOperationLabel = new javax.swing.JLabel();
        historyLabel = new javax.swing.JLabel();
        customerRegistrationButton = new javax.swing.JButton();
        staffRegistrationButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrawalButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        registeredCustomerButton = new javax.swing.JButton();
        depositDetailsButton = new javax.swing.JButton();
        withdrawalDetailsButton = new javax.swing.JButton();
        loginDetailsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openNewFolder = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveItem = new javax.swing.JMenuItem();
        printItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        profileItem = new javax.swing.JMenuItem();
        editPassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/home.png"))); // NOI18N
        homeButton.setFocusable(false);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        toolBar.add(homeButton);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/undo.png"))); // NOI18N
        backButton.setFocusable(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(backButton);

        splitPane.setDividerLocation(170);

        bankOperationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bankOperationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bankOperationLabel.setText("BANK OPERATION");

        historyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        historyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyLabel.setText("HISTORY");

        customerRegistrationButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        customerRegistrationButton.setText("Customer Registration");
        customerRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegistrationButtonActionPerformed(evt);
            }
        });

        staffRegistrationButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        staffRegistrationButton.setText("Staff Registration");
        staffRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRegistrationButtonActionPerformed(evt);
            }
        });

        depositButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawalButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        withdrawalButton.setText("Withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton5.setText("Money Transfer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        registeredCustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        registeredCustomerButton.setText("Registered Customer");
        registeredCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredCustomerButtonActionPerformed(evt);
            }
        });

        depositDetailsButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        depositDetailsButton.setText("Deposit Details");

        withdrawalDetailsButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        withdrawalDetailsButton.setText("Withdrawal");
        withdrawalDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalDetailsButtonActionPerformed(evt);
            }
        });

        loginDetailsButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loginDetailsButton.setText("Login Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bankOperationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(withdrawalDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registeredCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerRegistrationButton)
                            .addComponent(staffRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bankOperationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(customerRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(historyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registeredCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawalDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        splitPane.setLeftComponent(jPanel1);

        jPanel2.setLayout(null);

        mainPanel.setLayout(null);

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/bank.jpg"))); // NOI18N
        mainPanel.add(label);
        label.setBounds(0, 0, 940, 530);

        jPanel2.add(mainPanel);
        mainPanel.setBounds(0, 0, 940, 530);

        splitPane.setRightComponent(jPanel2);

        clock.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        centerPanel.setLayout(null);

        jMenu1.setText("File");

        openNewFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openNewFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/folder1.png"))); // NOI18N
        openNewFolder.setText("Open Folder");
        jMenu1.add(openNewFolder);
        jMenu1.add(jSeparator2);

        saveItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/save1.png"))); // NOI18N
        saveItem.setText("Save");
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveItem);

        printItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/print1.png"))); // NOI18N
        printItem.setText("Print");
        jMenu1.add(printItem);
        jMenu1.add(jSeparator1);

        exitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/shutdown.png"))); // NOI18N
        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.add(jSeparator3);

        profileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        profileItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/profile.png"))); // NOI18N
        profileItem.setText("Edit Profile");
        jMenu2.add(profileItem);

        editPassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        editPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/password.png"))); // NOI18N
        editPassword.setText("Edit Password");
        editPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordActionPerformed(evt);
            }
        });
        jMenu2.add(editPassword);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveItemActionPerformed

    private void customerRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRegistrationButtonActionPerformed
        // TODO add your handling code here:
        new CustomerRegisterForm().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_customerRegistrationButtonActionPerformed

    private void editPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_editPasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null,"Do you real need to close","Quit info",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(option==JOptionPane.YES_OPTION)
            dispose();
        else if(option==1)
            new BankHome().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null,"Do you need to Exit","Exit info",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(option==JOptionPane.YES_OPTION){
            new FrontForm().setVisible(true);
            this.dispose();
        }
        else
            return;
            
    }//GEN-LAST:event_exitItemActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void staffRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRegistrationButtonActionPerformed
        // TODO add your handling code here:
        new StaffRegisterForm().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_staffRegistrationButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        new DepositForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        // TODO add your handling code here:
        new WithdrawalForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new TransferForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void withdrawalDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawalDetailsButtonActionPerformed

    private void registeredCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredCustomerButtonActionPerformed
        // TODO add your handling code here:
        new RegisteredCustomer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredCustomerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex){
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bankOperationLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel clock;
    private javax.swing.JButton customerRegistrationButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton depositDetailsButton;
    private javax.swing.JMenuItem editPassword;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JLabel historyLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel label;
    private javax.swing.JButton loginDetailsButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem openNewFolder;
    private javax.swing.JMenuItem printItem;
    private javax.swing.JMenuItem profileItem;
    private javax.swing.JButton registeredCustomerButton;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton staffRegistrationButton;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JButton withdrawalButton;
    private javax.swing.JButton withdrawalDetailsButton;
    // End of variables declaration//GEN-END:variables
}
