/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.awt.Color;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author John T Lazaro
 */
public class CustomerPassword extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPassword
     */
    private Sql sq;
    public CustomerPassword() {
        initComponents();
        setLocationRelativeTo(null);
        passwordField.setVisible(false);
        confirmPasswordField.setVisible(false);
        enterPasswordLabel.setVisible(false);
        enterConfirmPassowordLabel.setVisible(false);
        signUpButton.setVisible(false);
        signInButton.setVisible(false);
    }
    //check method
    public void check(){
         sq=new Sql();
        String accountNumber=accountNumberField.getText();
        try{
            String password=sq.getAccountOwner(accountNumber);
            if("new".compareTo(password)==0){
                passwordField.setVisible(true);
                confirmPasswordField.setVisible(true);
                enterPasswordLabel.setVisible(true);
                enterConfirmPassowordLabel.setVisible(true);
                signUpButton.setVisible(true);
                okTickLabel.setVisible(true);
                passwordField.requestFocus();
                
            }else{
                passwordField.setVisible(true);
                okTickLabel.setVisible(true);
                enterPasswordLabel.setVisible(true);
                signInButton.setVisible(true);
                passwordField.requestFocus();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Account does not Exist","Login info",JOptionPane.ERROR_MESSAGE);
            signInButton.setVisible(false);
            okTickLabel.setVisible(false);
            passwordField.setVisible(false);
            accountNumberField.setText("");
            enterPasswordLabel.setVisible(false);
        }
    }
    public void signUpSendButton(){
        sq=new Sql();
        String accountNumber=accountNumberField.getText();
        String password1=new String(passwordField.getPassword());
        String password2=new String(confirmPasswordField.getPassword());
        String password = Base64.getEncoder().encodeToString(password1.getBytes());
        if(password1.equals(password2)){
            confirmPasswordMessage.setText("");
            sq.setNewPassword(password, accountNumber);
            new CustomerHomePage().setVisible(true);
            this.dispose();
        }else
        confirmPasswordMessage.setText("Unmatch Password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topLabel = new javax.swing.JLabel();
        accountNumberPanel = new javax.swing.JPanel();
        accountNumberField = new javax.swing.JTextField();
        okTickLabel = new javax.swing.JLabel();
        enterPasswordLabel = new javax.swing.JLabel();
        enterConfirmPassowordLabel = new javax.swing.JLabel();
        passwordMessage = new javax.swing.JLabel();
        confirmPasswordMessage = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        checkButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 532));
        setResizable(false);

        topLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        topLabel.setText("Please Enter Account Number");

        accountNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        accountNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNumberField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        accountNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberFieldActionPerformed(evt);
            }
        });

        okTickLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/ok.png"))); // NOI18N
        okTickLabel.setVisible(false);

        javax.swing.GroupLayout accountNumberPanelLayout = new javax.swing.GroupLayout(accountNumberPanel);
        accountNumberPanel.setLayout(accountNumberPanelLayout);
        accountNumberPanelLayout.setHorizontalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountNumberPanelLayout.createSequentialGroup()
                .addComponent(accountNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okTickLabel)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        accountNumberPanelLayout.setVerticalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountNumberField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(okTickLabel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        enterPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterPasswordLabel.setText("Enter Password");

        enterConfirmPassowordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enterConfirmPassowordLabel.setText("Confirm Password");

        passwordMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        confirmPasswordMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        signUpButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        confirmPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        confirmPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPasswordFieldKeyReleased(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        signInButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterConfirmPassowordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(confirmPasswordMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpButton)
                .addGap(373, 373, 373))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enterPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterConfirmPassowordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPasswordMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton)
                    .addComponent(signInButton))
                .addGap(304, 304, 304))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        this.check();
    }//GEN-LAST:event_checkButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        signUpSendButton();
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
        sq=new Sql();
        String accountNumber=accountNumberField.getText();
        String password=new String(passwordField.getPassword());
        try{
            String encryptedPassword=sq.getAccountOwner(accountNumber);
            byte[] decryptedPassword=Base64.getDecoder().decode(encryptedPassword);
            String password1=new String(decryptedPassword);
            if(password.equals(password1)){
                confirmPasswordMessage.setText("");
                new CustomerHomePage().setVisible(true);
                this.dispose();
            }else{
                passwordMessage.setText("Incorrect Password");
                passwordField.setText("");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Account does not Exist");
            accountNumberField.setText("");
        }
        
    }//GEN-LAST:event_signInButtonActionPerformed

    private void accountNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberFieldActionPerformed
        // TODO add your handling code here:
        this.check();
    }//GEN-LAST:event_accountNumberFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
        signUpSendButton();
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        // TODO add your handling code here:
        char[] chr=passwordField.getPassword();
        String password=new String(chr);
        String databasepassword=sq.getAccountOwner(accountNumberField.getText());
        if("new".compareTo(databasepassword)==0){
            if(password.length()<4){
                passwordMessage.setText("Weak Password");
                passwordMessage.setForeground(Color.RED);
            } 
            if(password.length()>4&&password.length()<7){
                passwordMessage.setText("Normal Password");
                passwordMessage.setForeground(new Color(0,0,0));
            }
            if(password.length()>7){
                passwordMessage.setText("Strong Password");
                passwordMessage.setForeground(new Color(0,102,51));
            }
            if(password.isEmpty())
                 passwordMessage.setText("");
        }
        
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void confirmPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPasswordFieldKeyReleased
        // TODO add your handling code here:
        String password=new String(passwordField.getPassword());
        String confirmPassword=new String(confirmPasswordField.getPassword());
        if(password.length()<confirmPassword.length()){
            confirmPasswordMessage.setText("Unmatch Password");
            confirmPasswordMessage.setForeground(Color.RED);
        }
        if(confirmPassword.isEmpty())
            confirmPasswordMessage.setText("");
        if(password.length()>confirmPassword.length())
            confirmPasswordMessage.setText("");
    }//GEN-LAST:event_confirmPasswordFieldKeyReleased

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberField;
    private javax.swing.JPanel accountNumberPanel;
    private javax.swing.JButton checkButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordMessage;
    private javax.swing.JLabel enterConfirmPassowordLabel;
    private javax.swing.JLabel enterPasswordLabel;
    private javax.swing.JLabel okTickLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordMessage;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
