/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John T Lazaro
 */
public class SelectAccount extends javax.swing.JPanel {

    /**
     * Creates new form SelectAccount
     */
    private Sql sql;
    private DefaultTableModel model;
    private ArrayList<Customer> customer;
    private Object[] row;
    
    public SelectAccount() {
        initComponents();
        accountReportTable.setVisible(false);
    }
    /**
     * method to print personal report
     * 
     */
    public void printAccountDetails(String account_no){
        customer=new ArrayList<>();
        sql=new Sql();
        try{
            customer=sql.getOneReport(account_no);
            model=(DefaultTableModel)accountReportTable.getModel();
            model.setRowCount(0);
            row=new Object[8];
            for(int i=0;i<customer.size();i++){
               row[0]=customer.get(i).getFname();
               row[1]=customer.get(i).getMname();
               row[2]=customer.get(i).getSurname();
               row[3]=customer.get(i).getDateOfBirth();
               row[4]=customer.get(i).getGander();
               row[5]=customer.get(i).getAccountName();
               row[6]=customer.get(i).getAccountNumber();
               row[7]=customer.get(i).getCardNumber();
               model.addRow(row);
            }
        }catch(Exception ex){
            javax.swing.JOptionPane.showMessageDialog(null,ex);
            //message.setText("Customer Doesn't Exist");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AccountReportTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        accountNumber = new javax.swing.JTextField();
        seacrhButton = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountReportTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(986, 547));

        AccountReportTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        AccountReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "MiddlName", "SurName", "gender", "Date Of Birth", "AccountName", "AccountNumber", "CardNumber", "Date Registered", "Status"
            }
        ));
        jScrollPane1.setViewportView(AccountReportTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        accountNumber.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        accountNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        accountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        seacrhButton.setText("Search");
        seacrhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seacrhButtonActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        accountReportTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        accountReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "MiddlName", "SurName", "gender", "Date Of Birth", "AccountName", "AccountNumber", "CardNumber", "Date Registered", "Status"
            }
        ));
        accountReportTable.setCellSelectionEnabled(true);
        accountReportTable.setPreferredSize(new java.awt.Dimension(986, 160));
        accountReportTable.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(accountReportTable);
        accountReportTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1062, 1062, 1062)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seacrhButton)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seacrhButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seacrhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seacrhButtonActionPerformed
        // TODO add your handling code here:
        String accountNo=accountNumber.getText();
        if(accountNo.isEmpty()){
            message.setText("*fill this field");
        }else{
            message.setText("");
            accountReportTable.setVisible(true);
            printAccountDetails(accountNo);
        }
        
    }//GEN-LAST:event_seacrhButtonActionPerformed

    private void accountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberActionPerformed
        // TODO add your handling code here:
        String accountNo=accountNumber.getText();
        if(accountNo.isEmpty()){
            message.setText("*fill this field");
        }else{
            message.setText("");
            accountReportTable.setVisible(true);
            printAccountDetails(accountNo);
        }
    }//GEN-LAST:event_accountNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccountReportTable;
    private javax.swing.JTextField accountNumber;
    private javax.swing.JTable accountReportTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel message;
    private javax.swing.JButton seacrhButton;
    // End of variables declaration//GEN-END:variables
}
