/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import static bank.DepositForm.referenceNumberRandomGenerator;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author John T Lazaro
 */
public class WithdrawalForm extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawalForm
     */
    private Sql sql;
    private Date date;
    private ArrayList<String> accountsno;
    public WithdrawalForm() {
        initComponents();
        setLocationRelativeTo(null);
        referenceNumber.setEditable(false);
        dateAndTime.setVisible(false);
        withdrawalAmount.setEditable(false);
    }
    void reset(){
        referenceNumber.setText("");
        accountName.setText("");
        accountNumber.setText("");
        withdrawalAmount.setText("");
        currencytype.setSelectedIndex(0);
        availableBalance.setText("");
        withdrawal.setText("");
        customerPhoto.setIcon(null);
        totalbalance.setText("");
        dateAndTime.setText("");
        okTick.setVisible(false);
        referenceNumber.setText("");
        withdrawalAmaountLabel.setText("");
       
       
    }
    public class TransactionTime extends Thread{
        @Override
        public void run(){
        while(true){
            try{
                Calendar calendar = Calendar.getInstance(); 
                date = calendar.getTime();
                dateAndTime.setText(date.toString());
                sleep(1000);
            }catch(InterruptedException e){
                
            }
        }
    }
    }
     public void checkButton(){
         File image;
        sql=new Sql();
        String accountnumber=accountNumber.getText();
        accountsno=new ArrayList<>();
        accountsno=sql.selectAllCustomer();
        try{
            if(accountsno.contains(accountnumber)){
                accountMessage.setText("");
                image=sql.selectCustomerImage(accountnumber);
                String accountname=sql.selectAllAccount(accountnumber);
                double accountBalance=sql.selectAccountBalance(accountnumber);
                okTick.setVisible(true);
                accountName.setText(accountname);
                availableBalance.setText(Double.toString(accountBalance));
                customerPhoto.setIcon(new ImageIcon(new ImageIcon(image.getAbsolutePath()).getImage().getScaledInstance(customerPhoto.getWidth(),customerPhoto.getHeight(),Image.SCALE_SMOOTH)));
                referenceNumber.setText(referenceNumberRandomGenerator());
                withdrawalAmount.requestFocus();
                withdrawalAmount.setEditable(true);
                new TransactionTime().start();
            }else{
                accountMessage.setText("Account doesn't Exist");
                accountNumber.setText("");
                this.reset();
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        homeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        accountNumberPanel = new javax.swing.JPanel();
        accountNumber = new javax.swing.JTextField();
        okTick = new javax.swing.JLabel();
        withdrawalLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        amaount = new javax.swing.JLabel();
        withdrawalAmount = new javax.swing.JTextField();
        currencytype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        withdrawalButton = new javax.swing.JButton();
        customerPhoto = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        availableBalance = new javax.swing.JLabel();
        withdrawal = new javax.swing.JLabel();
        totalbalance = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        referenceNumber = new javax.swing.JTextField();
        amaount1 = new javax.swing.JLabel();
        withdrawalAmaountLabel = new javax.swing.JLabel();
        accountMessage = new javax.swing.JLabel();
        dateAndTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1132, 591));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/home.png"))); // NOI18N
        homeButton.setFocusable(false);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(homeButton);

        accountNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12)), "Account Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        accountNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        accountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberActionPerformed(evt);
            }
        });

        okTick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/ok.png"))); // NOI18N
        okTick.setVisible(false);

        javax.swing.GroupLayout accountNumberPanelLayout = new javax.swing.GroupLayout(accountNumberPanel);
        accountNumberPanel.setLayout(accountNumberPanelLayout);
        accountNumberPanelLayout.setHorizontalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountNumberPanelLayout.createSequentialGroup()
                .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okTick))
        );
        accountNumberPanelLayout.setVerticalGroup(
            accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(accountNumber)
                .addComponent(okTick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        withdrawalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        withdrawalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/withdrawal.png"))); // NOI18N
        withdrawalLabel.setText("Withdrawal");
        withdrawalLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawalLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawalLabelMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Account Name:");

        accountName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        accountName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        amaount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amaount.setText("Amount");

        withdrawalAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        withdrawalAmount.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        withdrawalAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                withdrawalAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdrawalAmountKeyTyped(evt);
            }
        });

        currencytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TSHS" }));
        currencytype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencytypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ENTER AMOUNT YOU NEED TO WITHDRAWAL");

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        withdrawalButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        withdrawalButton.setText("withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });

        customerPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        checkButton.setText("check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Available Balance :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("withdrawal            :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Total Balance        :");

        availableBalance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        availableBalance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        withdrawal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        withdrawal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        totalbalance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalbalance.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(availableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(totalbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reference Number", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        referenceNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        referenceNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        referenceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(referenceNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(referenceNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        amaount1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amaount1.setText("reference number#");

        withdrawalAmaountLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        withdrawalAmaountLabel.setToolTipText("");

        accountMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        dateAndTime.setBorder(null);
        dateAndTime.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(accountName, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(amaount1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(accountNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(29, 29, 29)
                                                    .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(accountMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amaount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(withdrawalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currencytype, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(withdrawalAmaountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(withdrawalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(withdrawalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(accountNumberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accountMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountName, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                    .addComponent(customerPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(withdrawalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amaount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(currencytype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(withdrawalAmaountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(amaount1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(dateAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawalLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawalLabelMouseEntered
        // TODO add your handling code here:
        withdrawalLabel.setForeground(new Color(0,153,51));
    }//GEN-LAST:event_withdrawalLabelMouseEntered

    private void currencytypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencytypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencytypeActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        new BankHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        // TODO add your handling code here:
        sql=new Sql();
        String accountnumber=accountNumber.getText();
        String refNo=referenceNumber.getText();
        try{
            String transactionDate=dateAndTime.getText();
            if(withdrawalAmount.getText().isEmpty()){
                withdrawalAmaountLabel.setText("Please Enter Amount");
            }else{
                int option=JOptionPane.showConfirmDialog(null,"CONFIRM TRANSACTION","Withdrawal Info",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(option==JOptionPane.YES_OPTION){
                    double amountWithdrawal=(double)Integer.parseInt(withdrawalAmount.getText());
                    double accountBalance=sql.selectAccountBalance(accountnumber);
                    double totalBalance=accountBalance-amountWithdrawal;
                    sql.updateBalance(totalBalance,accountnumber);
                    sql.insertIntoWithdrawal(accountnumber,refNo,transactionDate,amountWithdrawal,totalBalance);
                    //JOptionPane.showMessageDialog(null,"Deposit Successful","Deposit info",JOptionPane.INFORMATION_MESSAGE);
                    int opt=JOptionPane.showConfirmDialog(null,"  Withdrawal Successful\nDo you need to Continue ?","Withdrawal info",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(opt==JOptionPane.YES_OPTION){
                        withdrawalAmount.setText("");
                        withdrawal.setText("");
                        totalbalance.setText("");
                        availableBalance.setText(Double.toString(sql.selectAccountBalance(accountnumber)));
                        referenceNumber.setText(referenceNumberRandomGenerator());
                    }
                    else{
                        this.reset();
                    }
                }
            }
     
        }catch(NumberFormatException ex){
            
        }
    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void referenceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceNumberActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // TODO add your handling code here:
        checkButton();
    }//GEN-LAST:event_checkButtonActionPerformed

    private void accountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberActionPerformed
        // TODO add your handling code here:
        checkButton();                    
    }//GEN-LAST:event_accountNumberActionPerformed

    private void withdrawalLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawalLabelMouseExited
        // TODO add your handling code here:
        withdrawalLabel.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_withdrawalLabelMouseExited

    private void withdrawalAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawalAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawalAmountKeyTyped

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null,"do you need to Reset","Reset Info",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(option==JOptionPane.YES_OPTION)
            this.reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void withdrawalAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawalAmountKeyReleased
        // TODO add your handling code here:
        sql=new Sql();
        double amountWithdrwal,accountBalance,totalBalance;
        String accountnumber=accountNumber.getText();
        try{
            withdrawalAmaountLabel.setText(" ");
            amountWithdrwal=(double)Integer.parseInt(withdrawalAmount.getText());
            accountBalance=sql.selectAccountBalance(accountnumber);
            if(accountBalance<amountWithdrwal){
                JOptionPane.showMessageDialog(null,"No enough Money","Withdrawal Info",JOptionPane.ERROR_MESSAGE);
                withdrawalAmount.setText("");
                withdrawal.setText("");
                totalbalance.setText("");
            }
            else{
                totalBalance=accountBalance-amountWithdrwal;
                withdrawal.setText(withdrawalAmount.getText());
                totalbalance.setText(Double.toString(totalBalance));
              }
        }catch(NumberFormatException ex){
            //JOptionPane.showMessageDialog(null,"Bad number format");
            withdrawalAmount.setText("");
            //withdrawalAmaountLabel.setText("Enter Decimal number");
            withdrawal.setText("");
        }
    }//GEN-LAST:event_withdrawalAmountKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountMessage;
    private javax.swing.JLabel accountName;
    private javax.swing.JTextField accountNumber;
    private javax.swing.JPanel accountNumberPanel;
    private javax.swing.JLabel amaount;
    private javax.swing.JLabel amaount1;
    private javax.swing.JLabel availableBalance;
    private javax.swing.JButton checkButton;
    private javax.swing.JComboBox<String> currencytype;
    private javax.swing.JLabel customerPhoto;
    private javax.swing.JTextField dateAndTime;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel okTick;
    private javax.swing.JTextField referenceNumber;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel totalbalance;
    private javax.swing.JLabel withdrawal;
    private javax.swing.JLabel withdrawalAmaountLabel;
    private javax.swing.JTextField withdrawalAmount;
    private javax.swing.JButton withdrawalButton;
    private javax.swing.JLabel withdrawalLabel;
    // End of variables declaration//GEN-END:variables
}
